VERDICTS = {"VERIFIED", "INCONCLUSIVE", "BLOCKED"}
PROOF_STATUSES = {"PROVEN", "INCONCLUSIVE", "NOT_FIXED", "REGRESSION", "UNREPRODUCIBLE", "ENVIRONMENT_MISMATCH"}
CLAIM_STATUSES = {"PROVEN", "SUPPORTED", "UNPROVEN", "CONTRADICTED", "NOT_APPLICABLE"}


def is_terminal_failure(verdict: str) -> bool:
    return verdict == "BLOCKED"
